name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# on:
#   pull_request:
#     branches:
#     - main

jobs:
  py-lint:
    runs-on: ubuntu-latest
    name: PyLint Workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@main

    - name: linting
      uses: programmingwithalex/pylinter@main
      with:
        python-root: '.'
        flake8-flags: '--count --show-source --statistics'
        mypy-flags: '--ignore-missing-imports'
        fail-on-isort: true
        skip-mypy: true
        mypy-ignore-dirs-files: 'folder1 folder2/main.py'
