name: Pylint

on: [push, pull_request]
  workflow_dispatch:

jobs:
  py-lint:
    runs-on: ubuntu-latest
    name: PyLint Workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@main

    - name: linting
      uses: programmingwithalex/pylinter@main
